// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/logic.proto

package logicpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_logic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_logic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_logic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_proto_logic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{3}
}

func (x *UserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_proto_logic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{4}
}

func (x *ListApplicationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListApplicationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SaveProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile       *Profile               `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProfileRequest) Reset() {
	*x = SaveProfileRequest{}
	mi := &file_proto_logic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProfileRequest) ProtoMessage() {}

func (x *SaveProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProfileRequest.ProtoReflect.Descriptor instead.
func (*SaveProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{5}
}

func (x *SaveProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UploadResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeRequest) Reset() {
	*x = UploadResumeRequest{}
	mi := &file_proto_logic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeRequest) ProtoMessage() {}

func (x *UploadResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeRequest.ProtoReflect.Descriptor instead.
func (*UploadResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{6}
}

func (x *UploadResumeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadResumeRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadResumeRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HrId          int64                  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_proto_logic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{7}
}

func (x *CreateJobRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *CreateJobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HrId          int64                  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_proto_logic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateJobRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *UpdateJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *UpdateJobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateJobRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ApplyJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   int64                  `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyJobRequest) Reset() {
	*x = ApplyJobRequest{}
	mi := &file_proto_logic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyJobRequest) ProtoMessage() {}

func (x *ApplyJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyJobRequest.ProtoReflect.Descriptor instead.
func (*ApplyJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyJobRequest) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *ApplyJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type AskAIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HrId          int64                  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskAIRequest) Reset() {
	*x = AskAIRequest{}
	mi := &file_proto_logic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskAIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskAIRequest) ProtoMessage() {}

func (x *AskAIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskAIRequest.ProtoReflect.Descriptor instead.
func (*AskAIRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{10}
}

func (x *AskAIRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *AskAIRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_logic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{11}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   int64                  `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Education     string                 `protobuf:"bytes,4,opt,name=education,proto3" json:"education,omitempty"`
	School        string                 `protobuf:"bytes,5,opt,name=school,proto3" json:"school,omitempty"`
	Experience    string                 `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Skills        string                 `protobuf:"bytes,7,opt,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_logic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{12}
}

func (x *Profile) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Profile) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *Profile) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *Profile) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *Profile) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerHrId     int64                  `protobuf:"varint,2,opt,name=owner_hr_id,json=ownerHrId,proto3" json:"owner_hr_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_logic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{13}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetOwnerHrId() int64 {
	if x != nil {
		return x.OwnerHrId
	}
	return 0
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CandidateId   int64                  `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	SignedUrl     string                 `protobuf:"bytes,5,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	UploadedAt    string                 `protobuf:"bytes,6,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_proto_logic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{14}
}

func (x *Resume) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resume) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *Resume) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Resume) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Resume) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *Resume) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CandidateId   int64                  `protobuf:"varint,3,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	ResumeId      int64                  `protobuf:"varint,4,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Job           *Job                   `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	Candidate     *User                  `protobuf:"bytes,7,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Profile       *Profile               `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	Resume        *Resume                `protobuf:"bytes,9,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_proto_logic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{15}
}

func (x *Application) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Application) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *Application) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *Application) GetResumeId() int64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

func (x *Application) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Application) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *Application) GetCandidate() *User {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *Application) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Application) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

type AIMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HrId          int64                  `protobuf:"varint,2,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIMessage) Reset() {
	*x = AIMessage{}
	mi := &file_proto_logic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIMessage) ProtoMessage() {}

func (x *AIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIMessage.ProtoReflect.Descriptor instead.
func (*AIMessage) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{16}
}

func (x *AIMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AIMessage) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *AIMessage) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AIMessage) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AIMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type JobListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobListResponse) Reset() {
	*x = JobListResponse{}
	mi := &file_proto_logic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListResponse) ProtoMessage() {}

func (x *JobListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobListResponse.ProtoReflect.Descriptor instead.
func (*JobListResponse) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{17}
}

func (x *JobListResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ApplicationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Application         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Applications  []*Application         `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationListResponse) Reset() {
	*x = ApplicationListResponse{}
	mi := &file_proto_logic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationListResponse) ProtoMessage() {}

func (x *ApplicationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationListResponse.ProtoReflect.Descriptor instead.
func (*ApplicationListResponse) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{18}
}

func (x *ApplicationListResponse) GetItems() []*Application {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ApplicationListResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ApplicationListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ApplicationListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ApplicationListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AIHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*AIMessage           `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIHistoryResponse) Reset() {
	*x = AIHistoryResponse{}
	mi := &file_proto_logic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIHistoryResponse) ProtoMessage() {}

func (x *AIHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIHistoryResponse.ProtoReflect.Descriptor instead.
func (*AIHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{19}
}

func (x *AIHistoryResponse) GetMessages() []*AIMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_logic_proto protoreflect.FileDescriptor

const file_proto_logic_proto_rawDesc = "" +
	"\n" +
	"\x11proto/logic.proto\x12\x10smartrecruitment\"\a\n" +
	"\x05Empty\"S\n" +
	"\vAuthRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\":\n" +
	"\fAuthResponse\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.smartrecruitment.UserR\x04user\"(\n" +
	"\rUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"c\n" +
	"\x17ListApplicationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"b\n" +
	"\x12SaveProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x123\n" +
	"\aprofile\x18\x02 \x01(\v2\x19.smartrecruitment.ProfileR\aprofile\"e\n" +
	"\x13UploadResumeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"_\n" +
	"\x10CreateJobRequest\x12\x13\n" +
	"\x05hr_id\x18\x01 \x01(\x03R\x04hrId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8e\x01\n" +
	"\x10UpdateJobRequest\x12\x13\n" +
	"\x05hr_id\x18\x01 \x01(\x03R\x04hrId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"K\n" +
	"\x0fApplyJobRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\x03R\vcandidateId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\"?\n" +
	"\fAskAIRequest\x12\x13\n" +
	"\x05hr_id\x18\x01 \x01(\x03R\x04hrId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xc4\x01\n" +
	"\aProfile\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\x03R\vcandidateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1c\n" +
	"\teducation\x18\x04 \x01(\tR\teducation\x12\x16\n" +
	"\x06school\x18\x05 \x01(\tR\x06school\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\tR\n" +
	"experience\x12\x16\n" +
	"\x06skills\x18\a \x01(\tR\x06skills\"\xa4\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\vowner_hr_id\x18\x02 \x01(\x03R\townerHrId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xb7\x01\n" +
	"\x06Resume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x03R\vcandidateId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x05 \x01(\tR\tsignedUrl\x12\x1f\n" +
	"\vuploaded_at\x18\x06 \x01(\tR\n" +
	"uploadedAt\"\xd9\x02\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12!\n" +
	"\fcandidate_id\x18\x03 \x01(\x03R\vcandidateId\x12\x1b\n" +
	"\tresume_id\x18\x04 \x01(\x03R\bresumeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12'\n" +
	"\x03job\x18\x06 \x01(\v2\x15.smartrecruitment.JobR\x03job\x124\n" +
	"\tcandidate\x18\a \x01(\v2\x16.smartrecruitment.UserR\tcandidate\x123\n" +
	"\aprofile\x18\b \x01(\v2\x19.smartrecruitment.ProfileR\aprofile\x120\n" +
	"\x06resume\x18\t \x01(\v2\x18.smartrecruitment.ResumeR\x06resume\"\x83\x01\n" +
	"\tAIMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x13\n" +
	"\x05hr_id\x18\x02 \x01(\x03R\x04hrId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"<\n" +
	"\x0fJobListResponse\x12)\n" +
	"\x04jobs\x18\x01 \x03(\v2\x15.smartrecruitment.JobR\x04jobs\"\xd8\x01\n" +
	"\x17ApplicationListResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.smartrecruitment.ApplicationR\x05items\x12A\n" +
	"\fapplications\x18\x02 \x03(\v2\x1d.smartrecruitment.ApplicationR\fapplications\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"L\n" +
	"\x11AIHistoryResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.smartrecruitment.AIMessageR\bmessages2\xc1\t\n" +
	"\fLogicService\x12I\n" +
	"\bRegister\x12\x1d.smartrecruitment.AuthRequest\x1a\x1e.smartrecruitment.AuthResponse\x12F\n" +
	"\x05Login\x12\x1d.smartrecruitment.AuthRequest\x1a\x1e.smartrecruitment.AuthResponse\x12L\n" +
	"\vSaveProfile\x12$.smartrecruitment.SaveProfileRequest\x1a\x17.smartrecruitment.Empty\x12H\n" +
	"\n" +
	"GetProfile\x12\x1f.smartrecruitment.UserIDRequest\x1a\x19.smartrecruitment.Profile\x12O\n" +
	"\fUploadResume\x12%.smartrecruitment.UploadResumeRequest\x1a\x18.smartrecruitment.Resume\x12O\n" +
	"\vParseResume\x12%.smartrecruitment.UploadResumeRequest\x1a\x19.smartrecruitment.Profile\x12F\n" +
	"\tCreateJob\x12\".smartrecruitment.CreateJobRequest\x1a\x15.smartrecruitment.Job\x12H\n" +
	"\tUpdateJob\x12\".smartrecruitment.UpdateJobRequest\x1a\x17.smartrecruitment.Empty\x12F\n" +
	"\bListJobs\x12\x17.smartrecruitment.Empty\x1a!.smartrecruitment.JobListResponse\x12P\n" +
	"\n" +
	"ListHRJobs\x12\x1f.smartrecruitment.UserIDRequest\x1a!.smartrecruitment.JobListResponse\x12L\n" +
	"\bApplyJob\x12!.smartrecruitment.ApplyJobRequest\x1a\x1d.smartrecruitment.Application\x12g\n" +
	"\x19ListCandidateApplications\x12\x1f.smartrecruitment.UserIDRequest\x1a).smartrecruitment.ApplicationListResponse\x12h\n" +
	"\x10ListApplications\x12).smartrecruitment.ListApplicationsRequest\x1a).smartrecruitment.ApplicationListResponse\x12D\n" +
	"\x05AskAI\x12\x1e.smartrecruitment.AskAIRequest\x1a\x1b.smartrecruitment.AIMessage\x12Q\n" +
	"\tAIHistory\x12\x1f.smartrecruitment.UserIDRequest\x1a#.smartrecruitment.AIHistoryResponseB1Z/smart-recruitment/web-gin-service/proto;logicpbb\x06proto3"

var (
	file_proto_logic_proto_rawDescOnce sync.Once
	file_proto_logic_proto_rawDescData []byte
)

func file_proto_logic_proto_rawDescGZIP() []byte {
	file_proto_logic_proto_rawDescOnce.Do(func() {
		file_proto_logic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logic_proto_rawDesc), len(file_proto_logic_proto_rawDesc)))
	})
	return file_proto_logic_proto_rawDescData
}

var file_proto_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_logic_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: smartrecruitment.Empty
	(*AuthRequest)(nil),             // 1: smartrecruitment.AuthRequest
	(*AuthResponse)(nil),            // 2: smartrecruitment.AuthResponse
	(*UserIDRequest)(nil),           // 3: smartrecruitment.UserIDRequest
	(*ListApplicationsRequest)(nil), // 4: smartrecruitment.ListApplicationsRequest
	(*SaveProfileRequest)(nil),      // 5: smartrecruitment.SaveProfileRequest
	(*UploadResumeRequest)(nil),     // 6: smartrecruitment.UploadResumeRequest
	(*CreateJobRequest)(nil),        // 7: smartrecruitment.CreateJobRequest
	(*UpdateJobRequest)(nil),        // 8: smartrecruitment.UpdateJobRequest
	(*ApplyJobRequest)(nil),         // 9: smartrecruitment.ApplyJobRequest
	(*AskAIRequest)(nil),            // 10: smartrecruitment.AskAIRequest
	(*User)(nil),                    // 11: smartrecruitment.User
	(*Profile)(nil),                 // 12: smartrecruitment.Profile
	(*Job)(nil),                     // 13: smartrecruitment.Job
	(*Resume)(nil),                  // 14: smartrecruitment.Resume
	(*Application)(nil),             // 15: smartrecruitment.Application
	(*AIMessage)(nil),               // 16: smartrecruitment.AIMessage
	(*JobListResponse)(nil),         // 17: smartrecruitment.JobListResponse
	(*ApplicationListResponse)(nil), // 18: smartrecruitment.ApplicationListResponse
	(*AIHistoryResponse)(nil),       // 19: smartrecruitment.AIHistoryResponse
}
var file_proto_logic_proto_depIdxs = []int32{
	11, // 0: smartrecruitment.AuthResponse.user:type_name -> smartrecruitment.User
	12, // 1: smartrecruitment.SaveProfileRequest.profile:type_name -> smartrecruitment.Profile
	13, // 2: smartrecruitment.Application.job:type_name -> smartrecruitment.Job
	11, // 3: smartrecruitment.Application.candidate:type_name -> smartrecruitment.User
	12, // 4: smartrecruitment.Application.profile:type_name -> smartrecruitment.Profile
	14, // 5: smartrecruitment.Application.resume:type_name -> smartrecruitment.Resume
	13, // 6: smartrecruitment.JobListResponse.jobs:type_name -> smartrecruitment.Job
	15, // 7: smartrecruitment.ApplicationListResponse.items:type_name -> smartrecruitment.Application
	15, // 8: smartrecruitment.ApplicationListResponse.applications:type_name -> smartrecruitment.Application
	16, // 9: smartrecruitment.AIHistoryResponse.messages:type_name -> smartrecruitment.AIMessage
	1,  // 10: smartrecruitment.LogicService.Register:input_type -> smartrecruitment.AuthRequest
	1,  // 11: smartrecruitment.LogicService.Login:input_type -> smartrecruitment.AuthRequest
	5,  // 12: smartrecruitment.LogicService.SaveProfile:input_type -> smartrecruitment.SaveProfileRequest
	3,  // 13: smartrecruitment.LogicService.GetProfile:input_type -> smartrecruitment.UserIDRequest
	6,  // 14: smartrecruitment.LogicService.UploadResume:input_type -> smartrecruitment.UploadResumeRequest
	6,  // 15: smartrecruitment.LogicService.ParseResume:input_type -> smartrecruitment.UploadResumeRequest
	7,  // 16: smartrecruitment.LogicService.CreateJob:input_type -> smartrecruitment.CreateJobRequest
	8,  // 17: smartrecruitment.LogicService.UpdateJob:input_type -> smartrecruitment.UpdateJobRequest
	0,  // 18: smartrecruitment.LogicService.ListJobs:input_type -> smartrecruitment.Empty
	3,  // 19: smartrecruitment.LogicService.ListHRJobs:input_type -> smartrecruitment.UserIDRequest
	9,  // 20: smartrecruitment.LogicService.ApplyJob:input_type -> smartrecruitment.ApplyJobRequest
	3,  // 21: smartrecruitment.LogicService.ListCandidateApplications:input_type -> smartrecruitment.UserIDRequest
	4,  // 22: smartrecruitment.LogicService.ListApplications:input_type -> smartrecruitment.ListApplicationsRequest
	10, // 23: smartrecruitment.LogicService.AskAI:input_type -> smartrecruitment.AskAIRequest
	3,  // 24: smartrecruitment.LogicService.AIHistory:input_type -> smartrecruitment.UserIDRequest
	2,  // 25: smartrecruitment.LogicService.Register:output_type -> smartrecruitment.AuthResponse
	2,  // 26: smartrecruitment.LogicService.Login:output_type -> smartrecruitment.AuthResponse
	0,  // 27: smartrecruitment.LogicService.SaveProfile:output_type -> smartrecruitment.Empty
	12, // 28: smartrecruitment.LogicService.GetProfile:output_type -> smartrecruitment.Profile
	14, // 29: smartrecruitment.LogicService.UploadResume:output_type -> smartrecruitment.Resume
	12, // 30: smartrecruitment.LogicService.ParseResume:output_type -> smartrecruitment.Profile
	13, // 31: smartrecruitment.LogicService.CreateJob:output_type -> smartrecruitment.Job
	0,  // 32: smartrecruitment.LogicService.UpdateJob:output_type -> smartrecruitment.Empty
	17, // 33: smartrecruitment.LogicService.ListJobs:output_type -> smartrecruitment.JobListResponse
	17, // 34: smartrecruitment.LogicService.ListHRJobs:output_type -> smartrecruitment.JobListResponse
	15, // 35: smartrecruitment.LogicService.ApplyJob:output_type -> smartrecruitment.Application
	18, // 36: smartrecruitment.LogicService.ListCandidateApplications:output_type -> smartrecruitment.ApplicationListResponse
	18, // 37: smartrecruitment.LogicService.ListApplications:output_type -> smartrecruitment.ApplicationListResponse
	16, // 38: smartrecruitment.LogicService.AskAI:output_type -> smartrecruitment.AIMessage
	19, // 39: smartrecruitment.LogicService.AIHistory:output_type -> smartrecruitment.AIHistoryResponse
	25, // [25:40] is the sub-list for method output_type
	10, // [10:25] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_logic_proto_init() }
func file_proto_logic_proto_init() {
	if File_proto_logic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logic_proto_rawDesc), len(file_proto_logic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logic_proto_goTypes,
		DependencyIndexes: file_proto_logic_proto_depIdxs,
		MessageInfos:      file_proto_logic_proto_msgTypes,
	}.Build()
	File_proto_logic_proto = out.File
	file_proto_logic_proto_goTypes = nil
	file_proto_logic_proto_depIdxs = nil
}
