// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/logic.proto

package logicpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogicService_Register_FullMethodName                  = "/smartrecruitment.LogicService/Register"
	LogicService_Login_FullMethodName                     = "/smartrecruitment.LogicService/Login"
	LogicService_SaveProfile_FullMethodName               = "/smartrecruitment.LogicService/SaveProfile"
	LogicService_GetProfile_FullMethodName                = "/smartrecruitment.LogicService/GetProfile"
	LogicService_UploadResume_FullMethodName              = "/smartrecruitment.LogicService/UploadResume"
	LogicService_ParseResume_FullMethodName               = "/smartrecruitment.LogicService/ParseResume"
	LogicService_CreateJob_FullMethodName                 = "/smartrecruitment.LogicService/CreateJob"
	LogicService_UpdateJob_FullMethodName                 = "/smartrecruitment.LogicService/UpdateJob"
	LogicService_ListJobs_FullMethodName                  = "/smartrecruitment.LogicService/ListJobs"
	LogicService_ListHRJobs_FullMethodName                = "/smartrecruitment.LogicService/ListHRJobs"
	LogicService_ApplyJob_FullMethodName                  = "/smartrecruitment.LogicService/ApplyJob"
	LogicService_ListCandidateApplications_FullMethodName = "/smartrecruitment.LogicService/ListCandidateApplications"
	LogicService_ListApplications_FullMethodName          = "/smartrecruitment.LogicService/ListApplications"
	LogicService_AskAI_FullMethodName                     = "/smartrecruitment.LogicService/AskAI"
	LogicService_AIHistory_FullMethodName                 = "/smartrecruitment.LogicService/AIHistory"
	LogicService_ClearAIHistory_FullMethodName            = "/smartrecruitment.LogicService/ClearAIHistory"
)

// LogicServiceClient is the client API for LogicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogicServiceClient interface {
	Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	SaveProfile(ctx context.Context, in *SaveProfileRequest, opts ...grpc.CallOption) (*Empty, error)
	GetProfile(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*Profile, error)
	UploadResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*Resume, error)
	ParseResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*Profile, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*Job, error)
	UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*Empty, error)
	ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobListResponse, error)
	ListHRJobs(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*JobListResponse, error)
	ApplyJob(ctx context.Context, in *ApplyJobRequest, opts ...grpc.CallOption) (*Application, error)
	ListCandidateApplications(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*ApplicationListResponse, error)
	ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ApplicationListResponse, error)
	AskAI(ctx context.Context, in *AskAIRequest, opts ...grpc.CallOption) (*AIMessage, error)
	AIHistory(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*AIHistoryResponse, error)
	ClearAIHistory(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*Empty, error)
}

type logicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicServiceClient(cc grpc.ClientConnInterface) LogicServiceClient {
	return &logicServiceClient{cc}
}

func (c *logicServiceClient) Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, LogicService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, LogicService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) SaveProfile(ctx context.Context, in *SaveProfileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LogicService_SaveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) GetProfile(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, LogicService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) UploadResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*Resume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resume)
	err := c.cc.Invoke(ctx, LogicService_UploadResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ParseResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, LogicService_ParseResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, LogicService_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LogicService_UpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ListJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, LogicService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ListHRJobs(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*JobListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobListResponse)
	err := c.cc.Invoke(ctx, LogicService_ListHRJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ApplyJob(ctx context.Context, in *ApplyJobRequest, opts ...grpc.CallOption) (*Application, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Application)
	err := c.cc.Invoke(ctx, LogicService_ApplyJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ListCandidateApplications(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*ApplicationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationListResponse)
	err := c.cc.Invoke(ctx, LogicService_ListCandidateApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ApplicationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationListResponse)
	err := c.cc.Invoke(ctx, LogicService_ListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) AskAI(ctx context.Context, in *AskAIRequest, opts ...grpc.CallOption) (*AIMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIMessage)
	err := c.cc.Invoke(ctx, LogicService_AskAI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) AIHistory(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*AIHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIHistoryResponse)
	err := c.cc.Invoke(ctx, LogicService_AIHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) ClearAIHistory(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LogicService_ClearAIHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicServiceServer is the server API for LogicService service.
// All implementations must embed UnimplementedLogicServiceServer
// for forward compatibility.
type LogicServiceServer interface {
	Register(context.Context, *AuthRequest) (*AuthResponse, error)
	Login(context.Context, *AuthRequest) (*AuthResponse, error)
	SaveProfile(context.Context, *SaveProfileRequest) (*Empty, error)
	GetProfile(context.Context, *UserIDRequest) (*Profile, error)
	UploadResume(context.Context, *UploadResumeRequest) (*Resume, error)
	ParseResume(context.Context, *UploadResumeRequest) (*Profile, error)
	CreateJob(context.Context, *CreateJobRequest) (*Job, error)
	UpdateJob(context.Context, *UpdateJobRequest) (*Empty, error)
	ListJobs(context.Context, *Empty) (*JobListResponse, error)
	ListHRJobs(context.Context, *UserIDRequest) (*JobListResponse, error)
	ApplyJob(context.Context, *ApplyJobRequest) (*Application, error)
	ListCandidateApplications(context.Context, *UserIDRequest) (*ApplicationListResponse, error)
	ListApplications(context.Context, *ListApplicationsRequest) (*ApplicationListResponse, error)
	AskAI(context.Context, *AskAIRequest) (*AIMessage, error)
	AIHistory(context.Context, *UserIDRequest) (*AIHistoryResponse, error)
	ClearAIHistory(context.Context, *UserIDRequest) (*Empty, error)
	mustEmbedUnimplementedLogicServiceServer()
}

// UnimplementedLogicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogicServiceServer struct{}

func (UnimplementedLogicServiceServer) Register(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedLogicServiceServer) Login(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLogicServiceServer) SaveProfile(context.Context, *SaveProfileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveProfile not implemented")
}
func (UnimplementedLogicServiceServer) GetProfile(context.Context, *UserIDRequest) (*Profile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedLogicServiceServer) UploadResume(context.Context, *UploadResumeRequest) (*Resume, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadResume not implemented")
}
func (UnimplementedLogicServiceServer) ParseResume(context.Context, *UploadResumeRequest) (*Profile, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseResume not implemented")
}
func (UnimplementedLogicServiceServer) CreateJob(context.Context, *CreateJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedLogicServiceServer) UpdateJob(context.Context, *UpdateJobRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedLogicServiceServer) ListJobs(context.Context, *Empty) (*JobListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedLogicServiceServer) ListHRJobs(context.Context, *UserIDRequest) (*JobListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHRJobs not implemented")
}
func (UnimplementedLogicServiceServer) ApplyJob(context.Context, *ApplyJobRequest) (*Application, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyJob not implemented")
}
func (UnimplementedLogicServiceServer) ListCandidateApplications(context.Context, *UserIDRequest) (*ApplicationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCandidateApplications not implemented")
}
func (UnimplementedLogicServiceServer) ListApplications(context.Context, *ListApplicationsRequest) (*ApplicationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedLogicServiceServer) AskAI(context.Context, *AskAIRequest) (*AIMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method AskAI not implemented")
}
func (UnimplementedLogicServiceServer) AIHistory(context.Context, *UserIDRequest) (*AIHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AIHistory not implemented")
}
func (UnimplementedLogicServiceServer) ClearAIHistory(context.Context, *UserIDRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearAIHistory not implemented")
}
func (UnimplementedLogicServiceServer) mustEmbedUnimplementedLogicServiceServer() {}
func (UnimplementedLogicServiceServer) testEmbeddedByValue()                      {}

// UnsafeLogicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicServiceServer will
// result in compilation errors.
type UnsafeLogicServiceServer interface {
	mustEmbedUnimplementedLogicServiceServer()
}

func RegisterLogicServiceServer(s grpc.ServiceRegistrar, srv LogicServiceServer) {
	// If the following call panics, it indicates UnimplementedLogicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogicService_ServiceDesc, srv)
}

func _LogicService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).Register(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).Login(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_SaveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).SaveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_SaveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).SaveProfile(ctx, req.(*SaveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).GetProfile(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_UploadResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).UploadResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_UploadResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).UploadResume(ctx, req.(*UploadResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ParseResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ParseResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ParseResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ParseResume(ctx, req.(*UploadResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_UpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).UpdateJob(ctx, req.(*UpdateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ListJobs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ListHRJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ListHRJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ListHRJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ListHRJobs(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ApplyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ApplyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ApplyJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ApplyJob(ctx, req.(*ApplyJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ListCandidateApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ListCandidateApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ListCandidateApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ListCandidateApplications(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ListApplications(ctx, req.(*ListApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_AskAI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskAIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).AskAI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_AskAI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).AskAI(ctx, req.(*AskAIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_AIHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).AIHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_AIHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).AIHistory(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_ClearAIHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ClearAIHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ClearAIHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ClearAIHistory(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogicService_ServiceDesc is the grpc.ServiceDesc for LogicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartrecruitment.LogicService",
	HandlerType: (*LogicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _LogicService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _LogicService_Login_Handler,
		},
		{
			MethodName: "SaveProfile",
			Handler:    _LogicService_SaveProfile_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _LogicService_GetProfile_Handler,
		},
		{
			MethodName: "UploadResume",
			Handler:    _LogicService_UploadResume_Handler,
		},
		{
			MethodName: "ParseResume",
			Handler:    _LogicService_ParseResume_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _LogicService_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _LogicService_UpdateJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _LogicService_ListJobs_Handler,
		},
		{
			MethodName: "ListHRJobs",
			Handler:    _LogicService_ListHRJobs_Handler,
		},
		{
			MethodName: "ApplyJob",
			Handler:    _LogicService_ApplyJob_Handler,
		},
		{
			MethodName: "ListCandidateApplications",
			Handler:    _LogicService_ListCandidateApplications_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _LogicService_ListApplications_Handler,
		},
		{
			MethodName: "AskAI",
			Handler:    _LogicService_AskAI_Handler,
		},
		{
			MethodName: "AIHistory",
			Handler:    _LogicService_AIHistory_Handler,
		},
		{
			MethodName: "ClearAIHistory",
			Handler:    _LogicService_ClearAIHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/logic.proto",
}
